### PR TITLE
Implement levels of packet minimal length checking

### PR DESCRIPTION
**Pull request by choroba**
See https://rt.cpan.org/Public/Bug/Display.html?id=114156 for the
reasons.

### CODE REVIEW

**Comment by choroba** [comment]
Greetings from PullRequest.Club. I wasn't sure how to add a new constructor option, so added a method to set the level instead. Comments welcome.

**Comment by djzort** [comment]
Hi @choroba 
I am extremely grateful for this PR and thank you muchly for it.
This finds me in the middle of a ridiculously busy month and I estimate i will be able to give it the attention it so very much deserves in a week or so.
Again, my thanks for contributing.

**Comment by obhessen** [comment]
Hi, are you able to merge this patch (or just remove the warnings of minimal size).
I'm receiving bootp from Juniper MX length 293 and would like these warnings
to shut up.

a.bootps > b.bootps: BOOTP/DHCP, Request from dc:xxxx:21 (oui Unknown), length 293, hops 1, xid 0x70f479f2, Flags [Broadcast]

**Comment by djzort** [comment]
@choroba I just realized that this pull request was provided before I relicensed to MIT and i have now merged and released it under that license. This was a mistake on my part and I need to confirm you are comfortable with your contribution being licensed under MIT rather than A1.0/GPL1.0 (aka "Perl 5 license")

**Comment by choroba** [comment]
No problem :-)

**Pull request merged**
